#!/usr/bin/env python3
"""TASK-4: Change parse_file to return ParsedFile with optional parse errors instead of Result"""
import base64, json, subprocess, sys
from pathlib import Path

TASK_ID = "TASK-4"
STEPS = json.loads('[{"before_b64": "dXNlIGNyYXRlOjpzY2hlbWE6OnsKICAgIEVycm9yLCBGaWxlSW5mbywgSW1wbEluZm8sIEltcGxJdGVtLCBJbXBsSXRlbUtpbmQsIEltcG9ydCwgSXRlbUF0dHJzLCBJdGVtS2luZCwgUHVibGljSXRlbSwKICAgIFJlRXhwb3J0LCBSZXN1bHQsIFN1Ym1vZHVsZURlY2wsCn07CnVzZSBzdGQ6OnBhdGg6OlBhdGg7CgovLyDilIDilIAgcGFyc2VfZmlsZSDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKCi8vLyBSZWFkIGFuZCBwYXJzZSBhIFJ1c3Qgc291cmNlIGZpbGUuIFJldHVybnMgdGhlIHJhdyBgc3luOjpGaWxlYCBBU1QgKG5lZWRlZAovLy8gYnkgYG1vZHVsZV90cmVlYCBmb3IgaW5saW5lIG1vZHVsZSBpdGVtIGV4dHJhY3Rpb24pIGFuZCB0aGUgZXh0cmFjdGVkCi8vLyBgRmlsZUluZm9gLiBPbiBwYXJzZSBmYWlsdXJlLCB3YXJucyB0byBzdGRlcnIgYW5kIHJldHVybnMgZW1wdHkgcmVzdWx0cy4KcHViIGZuIHBhcnNlX2ZpbGUocGF0aDogJlBhdGgpIC0+IFJlc3VsdDwoc3luOjpGaWxlLCBGaWxlSW5mbyk+IHsKICAgIGxldCBjb250ZW50ID0gc3RkOjpmczo6cmVhZF90b19zdHJpbmcocGF0aCkubWFwX2Vycih8c291cmNlfCBFcnJvcjo6RmlsZVJlYWQgewogICAgICAgIHBhdGg6IHBhdGgudG9fcGF0aF9idWYoKSwKICAgICAgICBzb3VyY2UsCiAgICB9KT87CgogICAgbGV0IGZpbGUgPSBtYXRjaCBzeW46OnBhcnNlX2ZpbGUoJmNvbnRlbnQpIHsKICAgICAgICBPayhmKSA9PiBmLAogICAgICAgIEVycihlKSA9PiB7CiAgICAgICAgICAgIGVwcmludGxuISgid2FybmluZzogZmFpbGVkIHRvIHBhcnNlIHt9OiB7fSIsIHBhdGguZGlzcGxheSgpLCBlKTsKICAgICAgICAgICAgbGV0IGVtcHR5ID0gc3luOjpGaWxlIHsKICAgICAgICAgICAgICAgIHNoZWJhbmc6IE5vbmUsCiAgICAgICAgICAgICAgICBhdHRyczogdmVjIVtdLAogICAgICAgICAgICAgICAgaXRlbXM6IHZlYyFbXSwKICAgICAgICAgICAgfTsKICAgICAgICAgICAgbGV0IGluZm8gPSBGaWxlSW5mbzo6ZGVmYXVsdCgpOwogICAgICAgICAgICByZXR1cm4gT2soKGVtcHR5LCBpbmZvKSk7CiAgICAgICAgfQogICAgfTsKCiAgICBsZXQgaW5mbyA9IEZpbGVJbmZvIHsKICAgICAgICBwdWJsaWNfaXRlbXM6IGV4dHJhY3RfcHVibGljX2l0ZW1zKCZmaWxlLml0ZW1zKSwKICAgICAgICBpbXBvcnRzOiBleHRyYWN0X2ltcG9ydHMoJmZpbGUuaXRlbXMpLAogICAgICAgIHJlX2V4cG9ydHM6IGV4dHJhY3RfcmVfZXhwb3J0cygmZmlsZS5pdGVtcyksCiAgICAgICAgc3VibW9kdWxlczogZXh0cmFjdF9zdWJtb2R1bGVzKCZmaWxlLml0ZW1zKSwKICAgICAgICBpbXBsczogZXh0cmFjdF9pbXBscygmZmlsZS5pdGVtcyksCiAgICB9OwoKICAgIE9rKChmaWxlLCBpbmZvKSkKfQ==", "after_b64": "dXNlIGNyYXRlOjpzY2hlbWE6OnsKICAgIEVycm9yLCBFcnJvckVudHJ5LCBFcnJvclNldmVyaXR5LCBGaWxlSW5mbywgSW1wbEluZm8sIEltcGxJdGVtLCBJbXBsSXRlbUtpbmQsIEltcG9ydCwKICAgIEl0ZW1BdHRycywgSXRlbUtpbmQsIFB1YmxpY0l0ZW0sIFJlRXhwb3J0LCBSZXN1bHQsIFN1Ym1vZHVsZURlY2wsCn07CnVzZSBzdGQ6OnBhdGg6OlBhdGg7CgovLyDilIDilIAgSW50ZXJuYWwgcGFyc2UgcmVzdWx0IHR5cGVzIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAoKLy8vIFJlc3VsdCBvZiBwYXJzaW5nIGEgUnVzdCBzb3VyY2UgZmlsZS4KLy8vCi8vLyBVbmxpa2UgYFJlc3VsdDxULCBFcnJvcj5gLCB0aGlzIHR5cGUgYWx3YXlzIHN1Y2NlZWRzIOKAlCBwYXJzZQovLy8gZmFpbHVyZXMgYXJlIHJlcG9ydGVkIGFzIGRhdGEsIG5vdCBhcyBlcnJvcnMsIHNvIHRoZSBjYWxsZXIKLy8vIGNhbiBjb250aW51ZSBwcm9jZXNzaW5nIG90aGVyIGZpbGVzLiBUaGUgY2FsbGVyIGNvbnN0cnVjdHMKLy8vIGBFcnJvckVudHJ5YCB2YWx1ZXMgZnJvbSBgU3luUGFyc2VFcnJvcmAgd2hlbiBuZWVkZWQuCnB1YiBzdHJ1Y3QgUGFyc2VkRmlsZSB7CiAgICBwdWIgYXN0OiBzeW46OkZpbGUsCiAgICBwdWIgZmlsZV9pbmZvOiBGaWxlSW5mbywKICAgIHB1YiBwYXJzZV9lcnJvcjogT3B0aW9uPFN5blBhcnNlRXJyb3I+LAp9CgovLy8gU3RydWN0dXJlZCBpbmZvcm1hdGlvbiBhYm91dCBhIHBhcnNlIGZhaWx1cmUuCnB1YiBzdHJ1Y3QgU3luUGFyc2VFcnJvciB7CiAgICBwdWIgbWVzc2FnZTogU3RyaW5nLAogICAgcHViIGxpbmU6IHVzaXplLAp9CgovLyDilIDilIAgcGFyc2VfZmlsZSDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKCi8vLyBSZWFkIGFuZCBwYXJzZSBhIFJ1c3Qgc291cmNlIGZpbGUuCi8vLwovLy8gT24gcGFyc2UgZmFpbHVyZSwgcmV0dXJucyB0aGUgb3JpZ2luYWwgZmlsZSBjb250ZW50IGFuZCBhCi8vLyBgU3luUGFyc2VFcnJvcmAgYWxvbmdzaWRlIGFuIGVtcHR5IGBGaWxlSW5mb2AuIENhbGxlcnMgdXNlIHRoZQovLy8gZXJyb3IgdG8gY29uc3RydWN0IGFuIGBFcnJvckVudHJ5YC4KcHViIGZuIHBhcnNlX2ZpbGUocGF0aDogJlBhdGgpIC0+IFBhcnNlZEZpbGUgewogICAgbGV0IGNvbnRlbnQgPSBtYXRjaCBzdGQ6OmZzOjpyZWFkX3RvX3N0cmluZyhwYXRoKSB7CiAgICAgICAgT2soYykgPT4gYywKICAgICAgICBFcnIoc291cmNlKSA9PiB7CiAgICAgICAgICAgIGxldCBlcnIgPSBTeW5QYXJzZUVycm9yIHsKICAgICAgICAgICAgICAgIG1lc3NhZ2U6IHNvdXJjZS50b19zdHJpbmcoKSwKICAgICAgICAgICAgICAgIGxpbmU6IDAsCiAgICAgICAgICAgIH07CiAgICAgICAgICAgIHJldHVybiBQYXJzZWRGaWxlIHsKICAgICAgICAgICAgICAgIGFzdDogc3luOjpGaWxlIHsKICAgICAgICAgICAgICAgICAgICBzaGViYW5nOiBOb25lLAogICAgICAgICAgICAgICAgICAgIGF0dHJzOiB2ZWMhW10sCiAgICAgICAgICAgICAgICAgICAgaXRlbXM6IHZlYyFbXSwKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICBmaWxlX2luZm86IEZpbGVJbmZvOjpkZWZhdWx0KCksCiAgICAgICAgICAgICAgICBwYXJzZV9lcnJvcjogU29tZShlcnIpLAogICAgICAgICAgICB9OwogICAgICAgIH0KICAgIH07CgogICAgbWF0Y2ggc3luOjpwYXJzZV9maWxlKCZjb250ZW50KSB7CiAgICAgICAgT2soZmlsZSkgPT4gewogICAgICAgICAgICBsZXQgZmlsZV9pbmZvID0gRmlsZUluZm8gewogICAgICAgICAgICAgICAgcHVibGljX2l0ZW1zOiBleHRyYWN0X3B1YmxpY19pdGVtcygmZmlsZS5pdGVtcyksCiAgICAgICAgICAgICAgICBpbXBvcnRzOiBleHRyYWN0X2ltcG9ydHMoJmZpbGUuaXRlbXMpLAogICAgICAgICAgICAgICAgcmVfZXhwb3J0czogZXh0cmFjdF9yZV9leHBvcnRzKCZmaWxlLml0ZW1zKSwKICAgICAgICAgICAgICAgIHN1Ym1vZHVsZXM6IGV4dHJhY3Rfc3VibW9kdWxlcygmZmlsZS5pdGVtcyksCiAgICAgICAgICAgICAgICBpbXBsczogZXh0cmFjdF9pbXBscygmZmlsZS5pdGVtcyksCiAgICAgICAgICAgIH07CiAgICAgICAgICAgIFBhcnNlZEZpbGUgewogICAgICAgICAgICAgICAgYXN0OiBmaWxlLAogICAgICAgICAgICAgICAgZmlsZV9pbmZvLAogICAgICAgICAgICAgICAgcGFyc2VfZXJyb3I6IE5vbmUsCiAgICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgIEVycihlKSA9PiB7CiAgICAgICAgICAgIGxldCBsaW5lID0gZS5zcGFuKCkuc3RhcnQoKS5saW5lOwogICAgICAgICAgICBsZXQgZXJyID0gU3luUGFyc2VFcnJvciB7CiAgICAgICAgICAgICAgICBtZXNzYWdlOiBlLnRvX3N0cmluZygpLAogICAgICAgICAgICAgICAgbGluZSwKICAgICAgICAgICAgfTsKICAgICAgICAgICAgUGFyc2VkRmlsZSB7CiAgICAgICAgICAgICAgICBhc3Q6IHN5bjo6RmlsZSB7CiAgICAgICAgICAgICAgICAgICAgc2hlYmFuZzogTm9uZSwKICAgICAgICAgICAgICAgICAgICBhdHRyczogdmVjIVtdLAogICAgICAgICAgICAgICAgICAgIGl0ZW1zOiB2ZWMhW10sCiAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgZmlsZV9pbmZvOiBGaWxlSW5mbzo6ZGVmYXVsdCgpLAogICAgICAgICAgICAgICAgcGFyc2VfZXJyb3I6IFNvbWUoZXJyKSwKICAgICAgICAgICAgfQogICAgICAgIH0KICAgIH0KfQoKcHViKGNyYXRlKSBmbiBidWlsZF9wYXJzZV9lcnJvcl9lbnRyeShwYXRoOiAmUGF0aCwgZXJyOiAmU3luUGFyc2VFcnJvcikgLT4gRXJyb3JFbnRyeSB7CiAgICBFcnJvckVudHJ5OjpidWlsZGVyKCkKICAgICAgICAuZmlsZShwYXRoLnRvX3N0cmluZ19sb3NzeSgpLnRvX3N0cmluZygpKQogICAgICAgIC5saW5lKGVyci5saW5lKQogICAgICAgIC5tZXNzYWdlKGVyci5tZXNzYWdlLmNsb25lKCkpCiAgICAgICAgLnNldmVyaXR5KEVycm9yU2V2ZXJpdHk6OkVycm9yKQogICAgICAgIC5raW5kKCJzeW5fcGFyc2VfZXJyb3IiLnRvX3N0cmluZygpKQogICAgICAgIC5idWlsZCgpCn0=", "target": "src/file_parser.rs", "index": 0, "is_create": false}]')

for step in STEPS:
    before = base64.b64decode(step["before_b64"]).decode()
    after = base64.b64decode(step["after_b64"]).decode()
    target = step["target"]
    idx = step["index"]
    is_create = step["is_create"]

    if is_create:
        target_path = Path(target)
        target_path.parent.mkdir(parents=True, exist_ok=True)
        target_path.write_text(after)
        print(f"OK {TASK_ID} change {idx}: created {target}")
    else:
        target_path = Path(target)
        content = target_path.read_text()
        if before not in content:
            print(f"FAILED {TASK_ID} change {idx}: pattern not found in {target}", file=sys.stderr)
            print(f"Expected (first 200 chars): {repr(before[:200])}", file=sys.stderr)
            sys.exit(1)

        result = subprocess.run(
            ["sd", "-F", "-A", "-n", "1", "--", before, after, target],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            print(f"FAILED {TASK_ID} change {idx}: sd error: {result.stderr}", file=sys.stderr)
            sys.exit(result.returncode)

        new_content = target_path.read_text()
        if after and after not in new_content:
            print(f"FAILED {TASK_ID} change {idx}: replacement not found after apply", file=sys.stderr)
            sys.exit(1)

        print(f"OK {TASK_ID} change {idx}: applied to {target}")

print(f"OK {TASK_ID}: all changes applied")
